apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: goapp

images:
- name: goapp
  newName: joaomarcosad/goapp
  newTag: 320cd1b09072c26372ec48f92203debdcafc7032
